apiVersion: v1
kind: Pod
metadata:
  annotations:
    description: Signal Sciences container with SigSci Agent and Module for Apache2
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"sigsci-apache-ubuntu1604-1714844172","uid":"38ba6229-dcea-11e6-b6c0-42d87950faa4","apiVersion":"extensions","resourceVersion":"67224"}}
  creationTimestamp: 2017-01-17T19:22:01Z
  generateName: sigsci-apache-ubuntu1604-1714844172-
  labels:
    app: sigsci-apache-ubuntu1604
    pod-template-hash: "1714844172"
    version: 1.14.4-1.4.6
  name: sigsci-apache-ubuntu1604-1714844172-46448
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    controller: true
    kind: ReplicaSet
    name: sigsci-apache-ubuntu1604-1714844172
    uid: 38ba6229-dcea-11e6-b6c0-42d87950faa4
  resourceVersion: "67246"
  selfLink: /api/v1/namespaces/default/pods/sigsci-apache-ubuntu1604-1714844172-46448
  uid: 38bdc0f7-dcea-11e6-b6c0-42d87950faa4
spec:
  containers:
  - env:
    - name: SIGSCI_ACCESSKEYID
      value: YOURIDHERE
    - name: SIGSCI_SECRETACCESSKEY
      value: YOURKEYHERE
    image: trickyhu/sigsci-apache-ubuntu1604:1.14.4-1.4.6
    imagePullPolicy: IfNotPresent
    name: sigsci-apache-ubuntu1604
    resources: {}
    securityContext:
      privileged: false
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-bpft2
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: minikube
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-bpft2
    secret:
      defaultMode: 420
      secretName: default-token-bpft2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-01-17T19:22:01Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2017-01-17T19:22:02Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2017-01-17T19:22:01Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9235265df1923d487032fc2947650f49fb213fdf01aba12a4f8c0127e9767569
    image: trickyhu/sigsci-apache-ubuntu1604:1.14.4-1.4.6
    imageID: docker://sha256:da80feb3f587c24318b24581cce1258eda6f651350466a3d40574ac4ae6a292e
    lastState: {}
    name: sigsci-apache-ubuntu1604
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2017-01-17T19:22:02Z
  hostIP: 192.168.99.101
  phase: Running
  podIP: 172.17.0.4
  startTime: 2017-01-17T19:22:01Z
