apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: Signal Sciences container with SigSci Agent and Module for Apache2
  creationTimestamp: 2017-01-17T19:22:01Z
  generation: 1
  labels:
    app: sigsci-apache-ubuntu1604
    version: 1.14.4-1.4.6
  name: sigsci-apache-ubuntu1604
  namespace: default
  resourceVersion: "67249"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/sigsci-apache-ubuntu1604
  uid: 38b964eb-dcea-11e6-b6c0-42d87950faa4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigsci-apache-ubuntu1604
      version: 1.14.4-1.4.6
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: Signal Sciences container with SigSci Agent and Module for Apache2
      creationTimestamp: null
      labels:
        app: sigsci-apache-ubuntu1604
        version: 1.14.4-1.4.6
      name: sigsci-apache-ubuntu1604
    spec:
      containers:
      - env:
        - name: SIGSCI_ACCESSKEYID
          value: YOURIDHERE
        - name: SIGSCI_SECRETACCESSKEY
          value: YOURKEYHERE
        image: trickyhu/sigsci-apache-ubuntu1604:1.14.4-1.4.6
        imagePullPolicy: IfNotPresent
        name: sigsci-apache-ubuntu1604
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-01-17T19:22:01Z
    lastUpdateTime: 2017-01-17T19:22:01Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
